# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

networks:
  test:
    name: fabric_test

services:
  chaincode_org1:
    image: ccm:latest
    container_name: ccm.chaincode.com
    environment:
      - CHAINCODE_CCID=ccm:9394ffa1c616986c7fbdec593dc7c8e986720a127036aa6df4233d2029bbc827
      - CHAINCODE_ADDRESS=ccm.chaincode.com:8090
      - TLS=true
    ports:
      - "8090:8090"
    networks:
      - test
