# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

networks:
  test:
    name: fabric_test

services:
  chaincode_org1:
    image: chaincode:latest
    container_name: org1.chaincode.com
    environment:
      - CHAINCODE_CCID=extBasic_1.0:c23de061b25e66267c4afd4eaecaee9c4b63717050fb9bffd3a70915de49722c
      - CHAINCODE_ADDRESS=org1.chaincode.com:8080
      - TLS=true
    ports:
      - "8080:8080"
    networks:
      - test
