# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

networks:
  test:
    name: fabric_test

services:
  chaincode_org1:
    image: chaincode:0.1.1
    container_name: poly.chaincode.com
    environment:
      - CHAINCODE_CCID=poly:4cde7faf7996d9524bfcb5f394a2a5b8b697732de31068c5a7027af33d9fd4b3
      - CHAINCODE_ADDRESS=poly.chaincode.com:8080
      - TLS=true
    ports:
      - "8080:8080"
    networks:
      - test
