# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

networks:
  test:
    name: fabric_test

services:
  chaincode_org1:
    image: chaincode:latest
    container_name: org1.chaincode.com
    environment:
      - CHAINCODE_CCID=mycc:24cab3bd4bd55c87867ad396d88309bd102554eb30cc1d7e488a7d58c56bece0
      - CHAINCODE_ADDRESS=org1.chaincode.com:8080
      - TLS=true
    ports:
      - "8080:8080"
    networks:
      - test
